### ISSUE TITLE
Responsive Design

### ISSUE THREAD

**Issue by digamber89** [Jori-Jo/Hotel-Design#2]
You are missing a very important piece when doing responsive design.
Check on responsive devices [Mobile, Tablet] - actual or simulated (not just resizing ) the browser.

**Comment by Jori-Jo** [comment]
I'll get back at you after revising the issues.

**Comment by Jori-Jo** [comment]
Issue: 
 Missing <meta> viewport element which gives the browser instructions on how to control the page's dimensions and scaling.
<meta name="viewport" content="width=device-width, initial-scale=1.0">
